name: Auto Publish Release

on:
  release:
    types: [created] # سيعمل بمجرد إنشاء مسودة

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publicize Release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ github.event.release.id }}
