name: Auto Publish Release
on:
  release:
    types: [created, edited] # سيعمل بمجرد إنشاء المسودة أو تعديلها بواسطة البرنامج

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Publicize Release
        uses: actions/github-script@v6
        with:
          script: |
            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
            // البحث عن أول مسودة (Draft) موجودة
            const draft = releases.find(r => r.draft === true);
            
            if (draft) {
              await github.rest.repos.updateRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: draft.id,
                draft: false,
                make_latest: "true"
              });
              console.log(`Successfully published Release ID: ${draft.id} Tag: ${draft.tag_name}`);
            } else {
              console.log("No draft release found to process.");
            }
